#!/bin/bash

# Directories
CONFIG_DIR="$HOME/.config/sketchybar"
ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

# Fonts
ICON_FONT="JetBrainsMono Nerd Font"
FONT="JetBrainsMono Nerd Font"

# Source Required Files
source "$CONFIG_DIR/settings.sh"
source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

# Bar Properties
BAR_PROPS=(
  height="$BAR_HEIGHT"
  shadow="$BAR_SHADOW"
  position="$BAR_POSITION"
  sticky="$BAR_STICKY"
  padding_right="$BAR_PADDING_RIGHT"
  padding_left="$BAR_PADDING_LEFT"
  corner_radius="$BAR_RADIUS"
  y_offset="$BAR_Y_OFFSET"
  margin="$BAR_MARGIN"
  blur_radius="$BAR_BLUR_RADIUS"
  notch_width="$BAR_NOTCH_WIDTH"
  background.color="$TRANSPARENT"
  color="$TRANSPARENT"
)

# Default Properties for Items
DEF_PROPS=(
  updates=when_shown
  icon.font="$ICON_FONT:Regular:16.0"
  icon.color="$WHITE"
  icon.padding_left="$ICON_PADDING_LEFT"
  icon.padding_right="$ICON_PADDING_RIGHT"
  label.font="$FONT:Regular:13.0"
  label.color="$WHITE"
  label.padding_left="$PADDING"
  label.padding_right="$LABEL_PADDING_RIGHT"
  background.color="$TRANSPARENT"
  background.padding_right="$PADDING"
  background.padding_left="$PADDING"
  background.height="$BACKGROUND_HEIGHT"
  background.corner_radius="$BACKGROUND_RADIUS"
  background.border_width="$BACKGROUND_BORDER_WIDTH"
  background.border_color="$LAVENDER"
)

# Configure SketchyBar
sketchybar --bar "${BAR_PROPS[@]}"
sketchybar --default "${DEF_PROPS[@]}"
sketchybar --add event spotify_change $SPOTIFY_CHANGE_EVENT

# Load Left Side Items
for item in apple spaces front_app; do
  source "$ITEM_DIR/$item.sh"
done

# Load Right Side Items
for item in time uptime battery sound wifi music; do
  source "$ITEM_DIR/$item.sh"
done

# Update SketchyBar
sketchybar --update
