live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/solarized_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "transparent"
dynamic_padding = false
opacity = 0.6
blur = true
startup_mode = "Maximized"
dynamic_title = true
option_as_alt = "Both"

[window.padding]
x = 25
y = 20


[font]
size = 18.0

[font.normal]
family = "CaskaydiaCove Nerd Font"

[cursor.style]
blinking = "On"
