
[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.35
blur = true
startup_mode = "SimpleFullscreen"
dynamic_title = true

[window.padding]
x = 25
y = 20

[font]
size = 18.0

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"

[cursor.style]
blinking = "On"

[general]
live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

